version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - elk_network
      - coinswarmnet
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.1
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - elk_network
      - coinswarmnet
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - logstash_config:/usr/share/logstash/config
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - elk_network
      - coinswarmnet
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elastic_data:
  logstash_config:

networks:
  elk_network:
    driver: overlay
