version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
    deploy:
      replicas: 1

  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - monitoring-net
    deploy:
      replicas: 1

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    deploy:
      replicas: 1

configs:
  prometheus.yml:
    external: true

volumes:
  influxdb-data:

networks:
  monitoring-net:
    external: true
