version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    deploy:
      replicas: 1
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - elk_network
      - coinswarmnet

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.1
    deploy:
      replicas: 2
    ports:
      - "12201:12201/udp"
    networks:
      - elk_network
      - coinswarmnet
    configs:
      - source: logstash_config
        target: /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    deploy:
      replicas: 1
    ports:
      - "5601:5601"
    networks:
      - elk_network
      - coinswarmnet
    depends_on:
      - elasticsearch
      - coinswarmnet
 
volumes:
  elastic_data:

configs:
  logstash_config:
    external: true
  
networks:
  elk_network:
    driver: overlay
  coinswarmnet:
    external: true